export enum StoryStatus {
  PENDING = 'PENDING',
  STORY_PROMPT_READY = 'STORY_PROMPT_READY',
  GENERATING_SCENES = 'GENERATING_SCENES',
  GENERATING_IMAGES = 'GENERATING_IMAGES',
  GENERATING_TTS = 'GENERATING_TTS',
  RENDERING_VIDEO = 'RENDERING_VIDEO',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
